# Generated by Django 4.0.4 on 2022-06-15 16:40

import apps.noticia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=255, verbose_name='Subtitulo')),
                ('cuerpo', models.CharField(max_length=255, verbose_name='Cuerpo')),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.noticia.models.img_directori, verbose_name='Imagen de la noticia')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
