# Generated by Django 4.0.4 on 2022-06-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiamodel',
            name='url',
            field=models.CharField(default='', max_length=400, verbose_name='Url de la noticia'),
        ),
    ]
