# Generated by Django 4.0.4 on 2022-06-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropiedadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior', models.CharField(default=0, max_length=255, unique=True, verbose_name='Interior o Bloque')),
                ('n_casa_o_apto', models.CharField(default=0, max_length=255, unique=True, verbose_name='Número o Letra de Interior')),
                ('t_integrantes', models.IntegerField(default=0, verbose_name='Total Integrantes')),
                ('ninos', models.BooleanField(default=False, verbose_name='Hay niños')),
                ('c_ninos', models.IntegerField(default=0, verbose_name='Cantidad de niños')),
                ('abuelos', models.BooleanField(default=False, verbose_name='Hay Personas 3ra edad')),
                ('c_abuelos', models.IntegerField(default=0, verbose_name='Cantidad de abuelos')),
                ('is_habitada', models.BooleanField(default=True, verbose_name='Esta habitada')),
                ('is_arriendo', models.BooleanField(default=False, verbose_name='Esta en arriendo')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
            },
        ),
    ]
