# Generated by Django 4.0.4 on 2022-06-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0002_alter_conjuntomodel_email_alter_conjuntomodel_name'),
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadmodel',
            name='fk_conjunto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conjunto.conjuntomodel'),
        ),
    ]
