# Generated by Django 4.0.4 on 2022-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Télefono'),
        ),
    ]
