# Generated by Django 4.0.4 on 2022-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
