# Generated by Django 4.0.4 on 2022-06-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0002_propiedadmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadmodel',
            name='is_active',
        ),
    ]
