# Generated by Django 4.0.4 on 2022-06-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedad', '0003_remove_propiedadmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadmodel',
            name='abuelos',
            field=models.BooleanField(default=False, verbose_name='Hay Personas 3ra edad'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='c_abuelos',
            field=models.IntegerField(default=0, verbose_name='Cantidad de abuelos'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='c_ninos',
            field=models.IntegerField(default=0, verbose_name='Cantidad de niños'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='interior',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='Interior o Bloque'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='is_arriendo',
            field=models.BooleanField(default=False, verbose_name='Esta en arriendo'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='is_habitada',
            field=models.BooleanField(default=True, verbose_name='Esta habitada'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='n_casa_o_apto',
            field=models.CharField(default=0, max_length=255, unique=True, verbose_name='Número o Letra de Interior'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='ninos',
            field=models.BooleanField(default=False, verbose_name='Hay niños'),
        ),
        migrations.AddField(
            model_name='propiedadmodel',
            name='t_integrantes',
            field=models.IntegerField(default=0, verbose_name='Total Integrantes'),
        ),
    ]
