# Generated by Django 4.0.4 on 2022-07-06 16:16

import apps.aviso.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_aviso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default=0, max_length=255, verbose_name='Descripción')),
                ('valor', models.IntegerField(default=0, max_length=255, verbose_name='Valor')),
                ('telefono', models.CharField(default=0, max_length=20, verbose_name='Teléfono de contacto')),
                ('imagen_1', models.ImageField(blank=True, max_length=255, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 1')),
                ('imagen_2', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 2')),
                ('imagen_3', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 3')),
                ('imagen_4', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 4')),
                ('imagen_5', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 5')),
                ('imagen_6', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 6')),
                ('imagen_7', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 7')),
                ('imagen_8', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 8')),
                ('imagen_9', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 9')),
                ('imagen_10', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.aviso.models.img_directori, verbose_name='Imagen 10')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('fk_tipoaviso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_aviso.tipoavisomodel')),
                ('fk_usuario_aviso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ('fecha',),
            },
        ),
    ]
