# Generated by Django 4.0.4 on 2022-06-06 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria_pedido', '0001_initial'),
        ('person', '0002_alter_personmodel_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casillero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriapedidomodel',
            name='fk_casillero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='casillero.casilleromodel'),
        ),
        migrations.AddField(
            model_name='auditoriapedidomodel',
            name='fk_persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.personmodel'),
        ),
        migrations.AddField(
            model_name='auditoriapedidomodel',
            name='fk_usuario_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
