# Generated by Django 4.0.4 on 2022-05-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo Electrónico')),
                ('telephone', models.CharField(blank=True, max_length=10, verbose_name='Telefono')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='img/conjunto/', verbose_name='Logo del conjunto')),
                ('Imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='img/conjunto/', verbose_name='Imagen del conjunto')),
                ('adress', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conjunto',
                'verbose_name_plural': 'Conjuntos',
            },
        ),
    ]
