# Generated by Django 4.0.4 on 2022-06-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuntomodel',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='conjuntomodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
    ]
