# Generated by Django 4.0.4 on 2022-06-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0002_alter_conjuntomodel_email_alter_conjuntomodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjuntomodel',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='conjuntomodel',
            name='about',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acerca de nosotros'),
        ),
        migrations.AddField(
            model_name='conjuntomodel',
            name='eslogan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Eslogan'),
        ),
    ]
