# Generated by Django 4.0.4 on 2022-06-14 15:24

import apps.conjunto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjunto', '0004_alter_conjuntomodel_imagen_alter_conjuntomodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuntomodel',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.conjunto.models.img_directori, verbose_name='Imagen del conjunto'),
        ),
        migrations.AlterField(
            model_name='conjuntomodel',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.conjunto.models.img_directori, verbose_name='Logo del conjunto'),
        ),
    ]
